name: Release
on:
  push:
    tags:
      - '*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build fatJar
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./gradlew -Pversion=${NEW_VERSION} buildFatJar --stacktrace

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/workflow-metrics-all.jar
          asset_name: workflow-metrics.jar
          tag: ${{ github.ref }}
          overwrite: true